###### Numpy is a python library used for working with arrays
###### It also has functions for working in domain of Linear Algebra and Matrices
###### Numpy stands for Numerical Python

In [4]:
!pip install numpy

pip install pandas

pip install sklearn

pip install seaborn
#conda install numpy

In [1]:
list1 = [1,2]

In [3]:
list1*2

[1, 2, 1, 2]

In [5]:
import numpy as np

import pandas as pd

In [6]:
np.version.version

'1.22.4'

In [ ]:
lst = [1,2,3,4]

In [ ]:
type(lst)

list

### Creating a Empty array

In [7]:
# Creating the emty array
ar = np.array([])
ar

# Where

    # ar -> variable name

    # np -> library name

    # array -> function helps to create the array

    # () -> Used for reprenting the function

    # [] -> represent the array

array([], dtype=float64)

In [8]:
type(ar)

numpy.ndarray

###  pass the values in the array

In [9]:
ar = np.array([1,2,5,9])
type(ar)

numpy.ndarray

In [10]:
ar

array([1, 2, 5, 9])

In [ ]:
ar

array([1, 2, 5, 9])

In [11]:
lst=np.array([3,12,3,4,5])

In [12]:
lst

array([ 3, 12,  3,  4,  5])

#### indexing part in the array

#### In python values are nothing but elements

#### in ndarray elements are going to seperated by using commas

In [ ]:
ar[0]

1

In [ ]:
ar[-2]

5

In [ ]:
ar[:3]

array([1, 2, 5])

In [13]:
list1 = [1,2,3]
ar1 = np.array([1,2,3])

In [16]:
list1*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [15]:
ar1*3

array([3, 6, 9])

#### Creating the array with different ways

In [20]:
ar = np.zeros(7)
ar

array([0., 0., 0., 0., 0., 0., 0.])

In [22]:
ar = np.ones(7)
ar

array([1., 1., 1., 1., 1., 1., 1.])

In [24]:
# arange values are starts at 0 to n-1
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
ar = np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Where

    # -> 2 represents the starting point

    # -> 10 is n-1 that is end point

ar = np.arange(2,10)
ar

#arange(a,b,c)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# Where

    # -> 2 represents the starting point

    # -> 15 is n-1 that is end point

    # - > 2 is difference between elements

    #output -- 0,2,4,6,8

ar = np.arange(0,10,3)
ar

array([0, 3, 6, 9])

In [28]:
ar = np.arange(1,15,4)
ar

array([ 1,  5,  9, 13])

In [29]:
def arrayinfo(a):
    print(a)
    print('Data Type of a variable a is: ',type(a))
    print('Number of dimensions:',a.ndim)
    print('Shape of the nd array:',a.shape)
    print('Number of elements in the nd array:',a.size)
    print('ndarray element datatype:',a.dtype)
    print('Memory allogation for each element:',a.itemsize)

In [30]:
arrayinfo(ar)

[ 1  5  9 13]
Data Type of a variable a is:  <class 'numpy.ndarray'>
Number of dimensions: 1
Shape of the nd array: (4,)
Number of elements in the nd array: 4
ndarray element datatype: int64
Memory allogation for each element: 8


#### Two Dimensional Arrays

In [31]:
arr = np.array([[1,2,5,8,10], [7,8,5,6,7],[3,5,7,9,10]])
arr

array([[ 1,  2,  5,  8, 10],
       [ 7,  8,  5,  6,  7],
       [ 3,  5,  7,  9, 10]])

In [ ]:
arrayinfo(arr)

[[ 1  2  5  8 10]
 [ 7  8  5  6  7]
 [ 3  5  7  9 10]]
Data Type of a variable a is:  <class 'numpy.ndarray'>
Number of dimensions: 2
Shape of the nd array: (3, 5)
Number of elements in the nd array: 15
ndarray element datatype: int32
Memory allogation for each element: 4


#### 2d array indexing

In [ ]:
arr = np.array([[1,5,6],[7,4,8],[2,3,9]])
arr

array([[1, 5, 6],
       [7, 4, 8],
       [2, 3, 9]])

In [ ]:
arr[0,0]

1

In [ ]:
arr[0,1]

5

In [ ]:
arr[-1,2]

9

In [ ]:
arr[-2,2]

8

In [ ]:
arr[-2,1]

4

In [ ]:
arr[-2,0]

7

In [ ]:
arr[]

In [ ]:
arr[-1,2]

8

In [ ]:
           c0    c1   c2

      r0   1     5    6          a[0,0]   a[0,1]    a[0,2]

a  =                          =
      r1   1     4    8          a[1,0]   a[1,1]    a[1,2]


# variable_name[row_indexvalue,column_indexvalue]

In [ ]:
arr

In [ ]:
arr[1,1]

In [ ]:
arr[0,2]

In [ ]:
arr [-1,2]

7

In [ ]:
arr[:,1]

##### arange

##### reshape

##### zero

##### ones

##### linspace

In [ ]:
import numpy as np
arr = np.array([[1,8,9],[8,7,6]])
arr

array([[1, 8, 9],
       [8, 7, 6]])

In [ ]:
for (x,y,z) in arr:
    print(x)
    print(y)
    print(z)

1
8
9
8
7
6


In [ ]:
arr[0]

array([1, 8, 9])

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
arr = np.array([[1,8,9],[8,7,6]])
arr

array([[1, 8, 9],
       [8, 7, 6]])

In [35]:
arr.shape

(2, 3)

In [41]:
arr_3_2 = arr.reshape(3,2)  #or arr.reshape(1,6) or arr.shape(6,1)

In [42]:
arr_3_2

array([[1, 8],
       [9, 8],
       [7, 6]])

In [40]:
arr_3_2.shape

(3, 2)

In [43]:
arr_1_6 = arr.reshape(1,6)
print(arr_1_6)
print(arr_1_6.shape)

[[1 8 9 8 7 6]]
(1, 6)


In [44]:
arr_6_1 = arr.reshape(6,1)
print(arr_6_1)
print(arr_6_1.shape)

[[1]
 [8]
 [9]
 [8]
 [7]
 [6]]
(6, 1)


In [45]:
arr.reshape(6,2)

ValueError: ignored

In [ ]:
#create numpy array with 3*4 shape and I want u to reshape the nupy array into 2*5  -----

In [ ]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
ar = np.array([1,8,9,8,7,6])
print(ar)

[1 8 9 8 7 6]


In [ ]:
arr = ar.reshape(3,2)
arr

array([[1, 8],
       [9, 8],
       [7, 6]])

In [ ]:
arr = ar.reshape(2,3)
arr

array([[1, 8, 9],
       [8, 7, 6]])

In [ ]:
arr_z = np.zeros(6)
arr_z

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr_z.reshape(2,3)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr_z = np.zeros(6).reshape(2,3)
arr_z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr_one = np.ones(8).reshape(8,1)
arr_one

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
# 1 -> Stating Value
# 5 -> Ending Value
# 2 -> difference between two elementys will be 2
arr_arrange = np.arange(1,8,3)
arr_arrange

array([1, 4, 7])

In [ ]:
# 1,3,5,7

In [49]:
arr_lnsp = np.linspace(2,10,4)
arr_lnsp

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [ ]:
# 1 -> Stating Value
# 5 -> Ending Value
# 20 -> count must be 20 Values
# note -> difference between any two values is same
arr_lnsp = np.linspace(1,5,20)
arr_lnsp

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

##### Scientific Claculation

##### Arthematic Operations

##### + - * / // %

##### sin log tanh max min sum mean mutable dtype

In [ ]:
a = np.array([[1,2],[4,5]])
b = np.array([[3,4],[6,7]])

In [ ]:
a

array([[1, 2],
       [4, 5]])

In [ ]:
b

array([[3, 4],
       [6, 7]])

In [ ]:
a+b

array([[ 4,  6],
       [10, 12]])

In [ ]:
a-b

array([[-2, -2],
       [-2, -2]])

In [ ]:
a*b

array([[ 3,  8],
       [24, 35]])

In [ ]:
a/b

array([[0.33333333, 0.5       ],
       [0.66666667, 0.71428571]])

In [ ]:
a//b

array([[0, 0],
       [0, 0]], dtype=int32)

In [ ]:
b//a

array([[3, 2],
       [1, 1]], dtype=int32)

In [ ]:
a%b

array([[1, 2],
       [4, 5]], dtype=int32)

In [ ]:
a

array([[1, 2],
       [4, 5]])

In [ ]:
d = a*5

In [ ]:
d

array([[ 5, 10],
       [20, 25]])

In [ ]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [-0.7568025 , -0.95892427]])

In [ ]:
np.log(a)

array([[0.        , 0.69314718],
       [1.38629436, 1.60943791]])

In [ ]:
a

array([[1, 2],
       [4, 5]])

In [ ]:
np.max(a)

5

In [ ]:
np.min(a)

1

In [ ]:
#numpy is mutable

#elements in the array going to change

In [ ]:
a

array([[1, 2],
       [4, 5]])

In [ ]:
a[0,0]=8
a

array([[8, 2],
       [4, 5]])

##### Copy

##### View

##### Transpose

#### Changing the data types

#####     -> While creating array we are changing datatype
    
#####     -> after creating array we are changing the datatype -> astype
    
###### Concatinating

##### hstack

##### vstack

##### ravel

##### flatten

In [51]:
arr = np.array([[1,5],[2,4]])
arr

array([[1, 5],
       [2, 4]])

In [ ]:
arr -- 2*3  --- if we transpose -- we will get 3*2 matrix


1*6 and 6*1

##### copy()

###### -> By using one variable array we are creating a duplicate and store it

###### -> both varibles own the elements

###### -> if we change in one varible other varible values are not reflecting

##### view()

###### -> By using one variable array we are creating a mirror and store it

###### -> both varibles own the elements

###### -> if we change in one varible other varible values are differ

In [ ]:
input_data1 = input_data

In [50]:
ar1 = arr.copy()

In [ ]:
ar1

array([[1, 5],
       [2, 4]])

In [ ]:
ar1[0,0] = 5
ar1

array([[5, 5],
       [2, 4]])

In [ ]:
arr

array([[1, 5],
       [2, 4]])

In [ ]:
ar_v = arr.view()
ar_v

array([[1, 5],
       [2, 4]])

In [ ]:
ar_v[0,0] = 5
ar_v

array([[5, 5],
       [2, 4]])

In [ ]:
ar_v

array([[5, 5],
       [2, 4]])

In [ ]:
arr

array([[5, 5],
       [2, 4]])

In [52]:
arr

array([[1, 5],
       [2, 4]])

In [53]:
# rows to columns or column to rows
arr.T

array([[1, 2],
       [5, 4]])

In [54]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [55]:
ar = np.array([[5,6],[7,8]])
ar

array([[5, 6],
       [7, 8]])

In [56]:
arr

array([[1, 2],
       [3, 4]])

In [ ]:
ar

array([[5, 6],
       [7, 8]])

In [ ]:
1 2
3 4    when we do concatenate row wise i.e axis = 0
5 6
7 8


1 2 5 6
3 4 7,8   when we do concatenate col wise i.e axis = 1

##### Concatination
###### To apply concatenation we are applying two arrays

In [57]:
arr_con = np.concatenate((arr,ar),axis =0)
arr_con

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [58]:
arr_con = np.concatenate((arr,ar),axis=1)
arr_con

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

##### hstack

##### vstack

##### column_stack

In [59]:
arr = np.array([1,2,3,4])

In [60]:
ar = np.array([5,6,7,8])

In [61]:
arr_vsck = np.vstack((arr,ar))
arr_vsck

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
arr_hsck = np.hstack((arr,ar))
arr_hsck

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
## column_stack is simply transpose of v_stack
arr_colsck = np.column_stack((arr,ar))
arr_colsck

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
arr_vsck.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
a --- 3*5

a.T -- 5*3

##### these things will helps to convert any dimension array into single dimension array

##### ravel

##### flatten

In [ ]:
arr_colsck

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
np.ravel(arr_colsck)

array([1, 5, 2, 6, 3, 7, 4, 8])

In [ ]:
arr_colsck.flatten()

array([1, 5, 2, 6, 3, 7, 4, 8])

In [ ]:
arr_colsck

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
arr_colsck.flatten(order='f')

array([1, 2, 3, 4, 5, 6, 7, 8])

#### List VS Numpy

##### we can do mathematical operations on numpy very easily as compared to list

In [66]:
lst = [1,2,3,4]

In [67]:
lst*3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [68]:
arr = np.array([1,2,3,4])

In [69]:
arr*3

array([ 3,  6,  9, 12])

##### array consumes less memory as compared to List

In [70]:
import sys

In [71]:
sys.getsizeof(lst)

88

In [72]:
arr.itemsize

8

##### using an array is faster than list

In [ ]:
## Addition of 1000 numbers using list and numpy both the ways

In [73]:
a = range(0,1000)
b = range(0,1000)

In [74]:
import time
t1 = time.time()
for i in range(0,1000):
    d = a[i]+b[i]
    print(d)
t2 = time.time()
total_time = t2-t1
print(total_time)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
200
202
204
206
208
210
212
214
216
218
220
222
224
226
228
230
232
234
236
238
240
242
244
246
248
250
252
254
256
258
260
262
264
266
268
270
272
274
276
278
280
282
284
286
288
290
292
294
296
298
300
302
304
306
308
310
312
314
316
318
320
322
324
326
328
330
332
334
336
338
340
342
344
346
348
350
352
354
356
358
360
362
364
366
368
370
372
374
376
378
380
382
384
386
388
390
392
394
396
398
400
402
404
406
408
410
412
414
416
418
420
422
424
426
428
430
432
434
436
438
440
442
444
446
448
450
452
454
456
458
460
462
464
466
468
470
472
474
476
478
480
482
484
486
488
490
492
494
496
498
500
502
504
506
508
510
512
514
516
518
520
522
524
526

In [75]:
print(total_time)

0.0507659912109375


In [76]:
a = np.arange(0,1000)
b = np.arange(0,1000)

In [77]:
import time
t1 = time.time()
for i in range(0,1000):
    d = a[i]+b[i]
    print(d)
t2 = time.time()
total_time = t2-t1

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
200
202
204
206
208
210
212
214
216
218
220
222
224
226
228
230
232
234
236
238
240
242
244
246
248
250
252
254
256
258
260
262
264
266
268
270
272
274
276
278
280
282
284
286
288
290
292
294
296
298
300
302
304
306
308
310
312
314
316
318
320
322
324
326
328
330
332
334
336
338
340
342
344
346
348
350
352
354
356
358
360
362
364
366
368
370
372
374
376
378
380
382
384
386
388
390
392
394
396
398
400
402
404
406
408
410
412
414
416
418
420
422
424
426
428
430
432
434
436
438
440
442
444
446
448
450
452
454
456
458
460
462
464
466
468
470
472
474
476
478
480
482
484
486
488
490
492
494
496
498
500
502
504
506
508
510
512
514
516
518
520
522
524
526

In [78]:
print(total_time)

0.3090357780456543


##### Random Generator

In [82]:
# will geneare one rando element
a = np.random.randint(0,100)
a

6

In [ ]:
import numpy as np

In [85]:
# will generate multiple elements , here generating 10 random numbers
a = np.random.randint(0,100,5)
a

array([74, 53, 22, 71, 32])

In [88]:
a = np.random.randint(0,1000,(3,4))
a

array([[924, 884,  32, 154],
       [764, 269,  73,  90],
       [212, 439, 894, 706]])

In [91]:
np.random.seed(30)
a = np.random.randint(0,100,(2,3))
a

array([[37, 37, 45],
       [45, 12, 23]])

In [90]:
np.random.seed(40)
a = np.random.randint(0,100,(2,3))
a

array([[70, 91,  7],
       [37, 56, 50]])

In [92]:
np.random.seed(30)
a = np.random.randint(0,100,(2,3))
a

array([[37, 37, 45],
       [45, 12, 23]])

In [ ]:
np.random.seed(10000)
a = np.random.randint(0,100,(2,3))
a

array([[12, 53, 31],
       [40, 47,  2]])

In [ ]:
np.random.seed(55)
a = np.random.randint(0,100,(2,3))
a

array([[77, 26, 39],
       [72, 29, 61]])

In [93]:
a = np.array([1,2,3,3,4,5,2,3,6,7])

In [94]:
# Getting Unique values from the numpy array
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7])

##### Changing the data types

######    -> While creating array we are changing datatype
    
######    -> after creating array we are changing the datatype -> astype

In [98]:
a = np.array([1,2,5.5,7,8,9])
a

array([1. , 2. , 5.5, 7. , 8. , 9. ])

In [99]:
type(a)

numpy.ndarray

In [100]:
a.dtype

dtype('float64')

In [101]:
a = np.array([1,2.3,5,7,8,9],dtype="int")
a

array([1, 2, 5, 7, 8, 9])

In [103]:
a.dtype

dtype('int64')

In [104]:
a = np.array([1,2.3,5,7,8,9])
a

array([1. , 2.3, 5. , 7. , 8. , 9. ])

In [105]:
type(a)

numpy.ndarray

In [106]:
a.dtype

dtype('float64')

In [107]:
a_int = a.astype("int")

In [109]:
a_int.dtype

dtype('int64')

In [110]:
b_float = a_int.astype("float")

In [111]:
b_float

array([1., 2., 5., 7., 8., 9.])